# Generated by Django 2.0.13 on 2020-10-07 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_tweetresultmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetresultmodel',
            name='accuracy',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='tweetresultmodel',
            name='prediction',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tweetresultmodel',
            name='tweetmsg',
            field=models.CharField(max_length=1000),
        ),
    ]
